spring:
  application:
    name: bigdata-service
  data:
    elasticsearch:
      repositories:
        enabled: true
#  data:
#    elasticsearch:
#      cluster-nodes: 127.0.0.1:9300

word:
  segmentation: N